### ISSUE TITLE
Bollyflix and multimovie

### ISSUE THREAD

**Issue by Mrunknow3** [phisher98/HindiProviders#66]
I'm watching Friends there sometime come multimovie most time aati hi nhi, bollyflix not come, I watch the boys bollyflix not come, I watched king fu panda 4 there bollyflix come but not work. 

I'm not saying multimovie not working is so buffering. 

And thanks for everything, I appreciate your work

**Comment by phisher98** [comment]
Yes because Series Support not there for Bollyflix yet also sometimes source limits requests so not a Extension issue if you copy link and then paste in Browser it will start Downloading so nothing from Extension end and MultiMovies is Working fine and does not buffer for me at all Its ISP issue maybe
