### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by ghost** [phisher98/HindiProviders#73]
MHDTV is down currently and a lot of the channels doesn't work either. Here's a better and reliable live tv source :
https://dlhd.so

**Comment by phisher98** [comment]
What's the category of this website also let me know which channels don't work as website changes their domains and sources a lot do hard to maintain it

**Comment by sosilly2004** [comment]
> What's the category of this website

Live tv. I am mainly interested in the sports section.

> which channels don't work

MHDTV has stopped working today in CS. Willow Cricket, Astro Cricket, Fox 501, all of the Sony sports in the Sony tab had already stopped working about a week ago.

> website changes their domains and sources a lot do hard to maintain it

I totally understand. I have used live tv m3u in the past and they are a PITA. MHDTV have reverted their domain again and that's why I thought of making this issue with a more stable website. Please don't burden yourself.

**Comment by phisher98** [comment]
Have you tried time4tv from Hex repo it looks similar

**Comment by sosilly2004** [comment]
Yes, it is the same site that I have requested. A lot of users loved it including me but it has stopped working now, unfortunately.

**Comment by phisher98** [comment]
Okay I will check if it could be fixed or need to add this one

**Comment by sosilly2004** [comment]
Thank you!
